Finalize Anyway migration to Kubernetes (#8)
* add secrets to deployment ymal

* update readme about secrets

* use Values

* changes to restore anyway DB from dump

* changes to restore anyway DB from dump

* restore DB on clean DB

* update anyway project for kubernetes minikub/production cluster

* update anyway project for kubernetes minikub/production cluster

*  update readme

* add script that install the requrements for minikube env

diff --git a/charts-external/anyway/templates/deployment.yaml b/charts-external/anyway/templates/deployment.yaml
--- a/charts-external/anyway/templates/deployment.yaml
+++ b/charts-external/anyway/templates/deployment.yaml
@@ -1,4 +1,5 @@
 {{ if .Values.enabled }}
+{{ if not .Values.disbaledDeployment }}
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
@@ -20,6 +21,8 @@ spec:
         resources: {{ .Values.resources }}
         ports:
         - containerPort: 8000
+        envFrom:
+        - secretRef: {"name": "anyway"}
         env:
         - name: POSTGRES_PASSWORD
           valueFrom: {"secretKeyRef":{"name":"db", "key":"POSTGRES_PASSWORD"}}
@@ -35,17 +38,20 @@ spec:
         - bash
         - "-c"
         - |
+          echo "INITIALIZE: ${INITIALIZE}"
           if [ "${INITIALIZE}" == "yes" ]; then
-            alembic upgrade 3c0d35fdbe2e &&\
-            alembic upgrade head &&\
-            python main.py process cbs &&\
-            python main.py process united --light
+            sleep 2 && ! alembic upgrade head && exit 1\
+            python main.py process cbs && echo python main.py process cbs && exit 1\
+            python main.py process united --light && echo python main.py process united --light && exit 1\
             [ "$?" != "0" ] && echo failed to initialize && exit 1
           else
-            ! alembic upgrade head && echo failed alembic upgrade && exit 1
+            echo "else"
+            # ! alembic upgrade head && echo failed alembic upgrade && exit 1
           fi
+          echo gunicorn anyway:app 
           gunicorn anyway:app &
           GUNICORN_PID=$!
+          echo celery worker -A anyway.clusters_calculator 
           celery worker -A anyway.clusters_calculator &
           CELERY_PID=$!
           while ( ps $GUNICORN_PID && ps $CELERY_PID ) >/dev/null 2>&1
@@ -57,4 +63,5 @@ spec:
         resources: {{ .Values.rabbitmqResources }}
         ports:
         - containerPort: 5672
+{{ end }}
 {{ end }}
